// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: analytics.sql

package db

import (
	"context"
	"database/sql"
)

const getConversationCacheHitRate = `-- name: GetConversationCacheHitRate :one
SELECT
    CAST(COALESCE(SUM(cache_read_tokens) * 100.0 / NULLIF(SUM(tokens_in), 0), 0.0) AS REAL) AS cache_hit_pct
FROM sub_calls
WHERE conversation_id = ? AND purpose = 'chat'
`

func (q *Queries) GetConversationCacheHitRate(ctx context.Context, conversationID sql.NullString) (float64, error) {
	row := q.db.QueryRowContext(ctx, getConversationCacheHitRate, conversationID)
	var cache_hit_pct float64
	err := row.Scan(&cache_hit_pct)
	return cache_hit_pct, err
}

const getConversationContextQuality = `-- name: GetConversationContextQuality :one
SELECT
    COUNT(*) AS total_turns,
    SUM(agent_used_search_tool) AS reactive_search_turns,
    AVG(context_hit_rate) AS avg_hit_rate,
    AVG(budget_used) AS avg_budget_used
FROM context_reports
WHERE conversation_id = ?
`

type GetConversationContextQualityRow struct {
	TotalTurns          int64           `json:"total_turns"`
	ReactiveSearchTurns sql.NullFloat64 `json:"reactive_search_turns"`
	AvgHitRate          sql.NullFloat64 `json:"avg_hit_rate"`
	AvgBudgetUsed       sql.NullFloat64 `json:"avg_budget_used"`
}

func (q *Queries) GetConversationContextQuality(ctx context.Context, conversationID string) (GetConversationContextQualityRow, error) {
	row := q.db.QueryRowContext(ctx, getConversationContextQuality, conversationID)
	var i GetConversationContextQualityRow
	err := row.Scan(
		&i.TotalTurns,
		&i.ReactiveSearchTurns,
		&i.AvgHitRate,
		&i.AvgBudgetUsed,
	)
	return i, err
}

const getConversationTokenUsage = `-- name: GetConversationTokenUsage :one
SELECT
    CAST(COALESCE(SUM(tokens_in), 0) AS INTEGER) AS total_in,
    CAST(COALESCE(SUM(tokens_out), 0) AS INTEGER) AS total_out,
    CAST(COALESCE(SUM(cache_read_tokens), 0) AS INTEGER) AS total_cache_hits,
    COUNT(*) AS total_calls,
    CAST(COALESCE(SUM(latency_ms), 0) AS INTEGER) AS total_latency_ms
FROM sub_calls
WHERE conversation_id = ? AND purpose = 'chat'
`

type GetConversationTokenUsageRow struct {
	TotalIn        int64 `json:"total_in"`
	TotalOut       int64 `json:"total_out"`
	TotalCacheHits int64 `json:"total_cache_hits"`
	TotalCalls     int64 `json:"total_calls"`
	TotalLatencyMs int64 `json:"total_latency_ms"`
}

func (q *Queries) GetConversationTokenUsage(ctx context.Context, conversationID sql.NullString) (GetConversationTokenUsageRow, error) {
	row := q.db.QueryRowContext(ctx, getConversationTokenUsage, conversationID)
	var i GetConversationTokenUsageRow
	err := row.Scan(
		&i.TotalIn,
		&i.TotalOut,
		&i.TotalCacheHits,
		&i.TotalCalls,
		&i.TotalLatencyMs,
	)
	return i, err
}

const getConversationToolUsage = `-- name: GetConversationToolUsage :many
SELECT
    tool_name,
    COUNT(*) AS call_count,
    AVG(duration_ms) AS avg_duration,
    SUM(CASE WHEN success = 0 THEN 1 ELSE 0 END) AS failure_count
FROM tool_executions
WHERE conversation_id = ?
GROUP BY tool_name
`

type GetConversationToolUsageRow struct {
	ToolName     string          `json:"tool_name"`
	CallCount    int64           `json:"call_count"`
	AvgDuration  sql.NullFloat64 `json:"avg_duration"`
	FailureCount sql.NullFloat64 `json:"failure_count"`
}

func (q *Queries) GetConversationToolUsage(ctx context.Context, conversationID string) ([]GetConversationToolUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, getConversationToolUsage, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConversationToolUsageRow
	for rows.Next() {
		var i GetConversationToolUsageRow
		if err := rows.Scan(
			&i.ToolName,
			&i.CallCount,
			&i.AvgDuration,
			&i.FailureCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
