// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: brain.sql

package db

import (
	"context"
	"database/sql"
)

const deleteBrainDocumentByPath = `-- name: DeleteBrainDocumentByPath :exec
DELETE FROM brain_documents
WHERE project_id = ?
  AND path = ?
`

type DeleteBrainDocumentByPathParams struct {
	ProjectID string `json:"project_id"`
	Path      string `json:"path"`
}

func (q *Queries) DeleteBrainDocumentByPath(ctx context.Context, arg DeleteBrainDocumentByPathParams) error {
	_, err := q.db.ExecContext(ctx, deleteBrainDocumentByPath, arg.ProjectID, arg.Path)
	return err
}

const deleteBrainLinksForSource = `-- name: DeleteBrainLinksForSource :exec
DELETE FROM brain_links
WHERE project_id = ?
  AND source_path = ?
`

type DeleteBrainLinksForSourceParams struct {
	ProjectID  string `json:"project_id"`
	SourcePath string `json:"source_path"`
}

func (q *Queries) DeleteBrainLinksForSource(ctx context.Context, arg DeleteBrainLinksForSourceParams) error {
	_, err := q.db.ExecContext(ctx, deleteBrainLinksForSource, arg.ProjectID, arg.SourcePath)
	return err
}

const getBrainDocumentByPath = `-- name: GetBrainDocumentByPath :one
SELECT id, project_id, path, title, content_hash, tags, frontmatter, token_count,
       created_by, source_conversation_id, created_at, updated_at
FROM brain_documents
WHERE project_id = ?
  AND path = ?
`

type GetBrainDocumentByPathParams struct {
	ProjectID string `json:"project_id"`
	Path      string `json:"path"`
}

func (q *Queries) GetBrainDocumentByPath(ctx context.Context, arg GetBrainDocumentByPathParams) (BrainDocument, error) {
	row := q.db.QueryRowContext(ctx, getBrainDocumentByPath, arg.ProjectID, arg.Path)
	var i BrainDocument
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Path,
		&i.Title,
		&i.ContentHash,
		&i.Tags,
		&i.Frontmatter,
		&i.TokenCount,
		&i.CreatedBy,
		&i.SourceConversationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBrainLink = `-- name: InsertBrainLink :exec
INSERT INTO brain_links (
    project_id,
    source_path,
    target_path,
    link_text
) VALUES (
    ?, ?, ?, ?
)
`

type InsertBrainLinkParams struct {
	ProjectID  string         `json:"project_id"`
	SourcePath string         `json:"source_path"`
	TargetPath string         `json:"target_path"`
	LinkText   sql.NullString `json:"link_text"`
}

func (q *Queries) InsertBrainLink(ctx context.Context, arg InsertBrainLinkParams) error {
	_, err := q.db.ExecContext(ctx, insertBrainLink,
		arg.ProjectID,
		arg.SourcePath,
		arg.TargetPath,
		arg.LinkText,
	)
	return err
}

const listBrainDocumentsByProject = `-- name: ListBrainDocumentsByProject :many
SELECT id, project_id, path, title, content_hash, tags, frontmatter, token_count,
       created_by, source_conversation_id, created_at, updated_at
FROM brain_documents
WHERE project_id = ?
ORDER BY path
`

func (q *Queries) ListBrainDocumentsByProject(ctx context.Context, projectID string) ([]BrainDocument, error) {
	rows, err := q.db.QueryContext(ctx, listBrainDocumentsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BrainDocument
	for rows.Next() {
		var i BrainDocument
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Path,
			&i.Title,
			&i.ContentHash,
			&i.Tags,
			&i.Frontmatter,
			&i.TokenCount,
			&i.CreatedBy,
			&i.SourceConversationID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBrainDocument = `-- name: UpsertBrainDocument :exec
INSERT INTO brain_documents (
    project_id,
    path,
    title,
    content_hash,
    tags,
    frontmatter,
    token_count,
    created_by,
    source_conversation_id,
    created_at,
    updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT(project_id, path) DO UPDATE SET
    title = excluded.title,
    content_hash = excluded.content_hash,
    tags = excluded.tags,
    frontmatter = excluded.frontmatter,
    token_count = excluded.token_count,
    created_by = excluded.created_by,
    source_conversation_id = excluded.source_conversation_id,
    updated_at = excluded.updated_at
`

type UpsertBrainDocumentParams struct {
	ProjectID            string         `json:"project_id"`
	Path                 string         `json:"path"`
	Title                sql.NullString `json:"title"`
	ContentHash          string         `json:"content_hash"`
	Tags                 sql.NullString `json:"tags"`
	Frontmatter          sql.NullString `json:"frontmatter"`
	TokenCount           sql.NullInt64  `json:"token_count"`
	CreatedBy            sql.NullString `json:"created_by"`
	SourceConversationID sql.NullString `json:"source_conversation_id"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
}

func (q *Queries) UpsertBrainDocument(ctx context.Context, arg UpsertBrainDocumentParams) error {
	_, err := q.db.ExecContext(ctx, upsertBrainDocument,
		arg.ProjectID,
		arg.Path,
		arg.Title,
		arg.ContentHash,
		arg.Tags,
		arg.Frontmatter,
		arg.TokenCount,
		arg.CreatedBy,
		arg.SourceConversationID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}
