// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chains.sql

package db

import (
	"context"
	"database/sql"
)

const completeChain = `-- name: CompleteChain :exec
UPDATE chains
SET status = ?,
    summary = ?,
    completed_at = datetime('now'),
    updated_at = datetime('now')
WHERE id = ?
`

type CompleteChainParams struct {
	Status  string         `json:"status"`
	Summary sql.NullString `json:"summary"`
	ID      string         `json:"id"`
}

func (q *Queries) CompleteChain(ctx context.Context, arg CompleteChainParams) error {
	_, err := q.db.ExecContext(ctx, completeChain, arg.Status, arg.Summary, arg.ID)
	return err
}

const completeStep = `-- name: CompleteStep :exec
UPDATE steps
SET status = ?,
    verdict = ?,
    receipt_path = ?,
    tokens_used = ?,
    turns_used = ?,
    duration_secs = ?,
    exit_code = ?,
    error_message = ?,
    completed_at = datetime('now')
WHERE id = ?
`

type CompleteStepParams struct {
	Status       string         `json:"status"`
	Verdict      sql.NullString `json:"verdict"`
	ReceiptPath  sql.NullString `json:"receipt_path"`
	TokensUsed   int64          `json:"tokens_used"`
	TurnsUsed    int64          `json:"turns_used"`
	DurationSecs int64          `json:"duration_secs"`
	ExitCode     sql.NullInt64  `json:"exit_code"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

func (q *Queries) CompleteStep(ctx context.Context, arg CompleteStepParams) error {
	_, err := q.db.ExecContext(ctx, completeStep,
		arg.Status,
		arg.Verdict,
		arg.ReceiptPath,
		arg.TokensUsed,
		arg.TurnsUsed,
		arg.DurationSecs,
		arg.ExitCode,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const countResolverStepsForTaskContext = `-- name: CountResolverStepsForTaskContext :one
SELECT COUNT(*) FROM steps
WHERE chain_id = ? AND role = 'resolver' AND task_context = ?
`

type CountResolverStepsForTaskContextParams struct {
	ChainID     string         `json:"chain_id"`
	TaskContext sql.NullString `json:"task_context"`
}

func (q *Queries) CountResolverStepsForTaskContext(ctx context.Context, arg CountResolverStepsForTaskContextParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countResolverStepsForTaskContext, arg.ChainID, arg.TaskContext)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChain = `-- name: CreateChain :exec
INSERT INTO chains (
    id,
    source_specs,
    source_task,
    status,
    max_steps,
    max_resolver_loops,
    max_duration_secs,
    token_budget
) VALUES (?, ?, ?, 'running', ?, ?, ?, ?)
`

type CreateChainParams struct {
	ID               string         `json:"id"`
	SourceSpecs      sql.NullString `json:"source_specs"`
	SourceTask       sql.NullString `json:"source_task"`
	MaxSteps         int64          `json:"max_steps"`
	MaxResolverLoops int64          `json:"max_resolver_loops"`
	MaxDurationSecs  int64          `json:"max_duration_secs"`
	TokenBudget      int64          `json:"token_budget"`
}

func (q *Queries) CreateChain(ctx context.Context, arg CreateChainParams) error {
	_, err := q.db.ExecContext(ctx, createChain,
		arg.ID,
		arg.SourceSpecs,
		arg.SourceTask,
		arg.MaxSteps,
		arg.MaxResolverLoops,
		arg.MaxDurationSecs,
		arg.TokenBudget,
	)
	return err
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (chain_id, step_id, event_type, event_data)
VALUES (?, ?, ?, ?)
`

type CreateEventParams struct {
	ChainID   string         `json:"chain_id"`
	StepID    sql.NullString `json:"step_id"`
	EventType string         `json:"event_type"`
	EventData sql.NullString `json:"event_data"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.ExecContext(ctx, createEvent,
		arg.ChainID,
		arg.StepID,
		arg.EventType,
		arg.EventData,
	)
	return err
}

const createStep = `-- name: CreateStep :exec
INSERT INTO steps (
    id,
    chain_id,
    sequence_num,
    role,
    task,
    task_context,
    status
) VALUES (?, ?, ?, ?, ?, ?, 'pending')
`

type CreateStepParams struct {
	ID          string         `json:"id"`
	ChainID     string         `json:"chain_id"`
	SequenceNum int64          `json:"sequence_num"`
	Role        string         `json:"role"`
	Task        string         `json:"task"`
	TaskContext sql.NullString `json:"task_context"`
}

func (q *Queries) CreateStep(ctx context.Context, arg CreateStepParams) error {
	_, err := q.db.ExecContext(ctx, createStep,
		arg.ID,
		arg.ChainID,
		arg.SequenceNum,
		arg.Role,
		arg.Task,
		arg.TaskContext,
	)
	return err
}

const getChain = `-- name: GetChain :one
SELECT id, source_specs, source_task, status, summary, total_steps, total_tokens, total_duration_secs, resolver_loops, max_steps, max_resolver_loops, max_duration_secs, token_budget, started_at, completed_at, created_at, updated_at FROM chains WHERE id = ?
`

func (q *Queries) GetChain(ctx context.Context, id string) (Chain, error) {
	row := q.db.QueryRowContext(ctx, getChain, id)
	var i Chain
	err := row.Scan(
		&i.ID,
		&i.SourceSpecs,
		&i.SourceTask,
		&i.Status,
		&i.Summary,
		&i.TotalSteps,
		&i.TotalTokens,
		&i.TotalDurationSecs,
		&i.ResolverLoops,
		&i.MaxSteps,
		&i.MaxResolverLoops,
		&i.MaxDurationSecs,
		&i.TokenBudget,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStep = `-- name: GetStep :one
SELECT id, chain_id, sequence_num, role, task, task_context, status, verdict, receipt_path, tokens_used, turns_used, duration_secs, exit_code, error_message, started_at, completed_at, created_at FROM steps WHERE id = ?
`

func (q *Queries) GetStep(ctx context.Context, id string) (Step, error) {
	row := q.db.QueryRowContext(ctx, getStep, id)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.ChainID,
		&i.SequenceNum,
		&i.Role,
		&i.Task,
		&i.TaskContext,
		&i.Status,
		&i.Verdict,
		&i.ReceiptPath,
		&i.TokensUsed,
		&i.TurnsUsed,
		&i.DurationSecs,
		&i.ExitCode,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listChains = `-- name: ListChains :many
SELECT id, source_specs, source_task, status, summary, total_steps, total_tokens, total_duration_secs, resolver_loops, max_steps, max_resolver_loops, max_duration_secs, token_budget, started_at, completed_at, created_at, updated_at FROM chains ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListChains(ctx context.Context, limit int64) ([]Chain, error) {
	rows, err := q.db.QueryContext(ctx, listChains, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Chain
	for rows.Next() {
		var i Chain
		if err := rows.Scan(
			&i.ID,
			&i.SourceSpecs,
			&i.SourceTask,
			&i.Status,
			&i.Summary,
			&i.TotalSteps,
			&i.TotalTokens,
			&i.TotalDurationSecs,
			&i.ResolverLoops,
			&i.MaxSteps,
			&i.MaxResolverLoops,
			&i.MaxDurationSecs,
			&i.TokenBudget,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByChain = `-- name: ListEventsByChain :many
SELECT id, chain_id, step_id, event_type, event_data, created_at FROM events WHERE chain_id = ? ORDER BY id ASC
`

func (q *Queries) ListEventsByChain(ctx context.Context, chainID string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByChain, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.StepID,
			&i.EventType,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByChainSince = `-- name: ListEventsByChainSince :many
SELECT id, chain_id, step_id, event_type, event_data, created_at FROM events
WHERE chain_id = ? AND id > ?
ORDER BY id ASC
`

type ListEventsByChainSinceParams struct {
	ChainID string `json:"chain_id"`
	ID      int64  `json:"id"`
}

func (q *Queries) ListEventsByChainSince(ctx context.Context, arg ListEventsByChainSinceParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByChainSince, arg.ChainID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.StepID,
			&i.EventType,
			&i.EventData,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStepsByChain = `-- name: ListStepsByChain :many
SELECT id, chain_id, sequence_num, role, task, task_context, status, verdict, receipt_path, tokens_used, turns_used, duration_secs, exit_code, error_message, started_at, completed_at, created_at FROM steps WHERE chain_id = ? ORDER BY sequence_num ASC
`

func (q *Queries) ListStepsByChain(ctx context.Context, chainID string) ([]Step, error) {
	rows, err := q.db.QueryContext(ctx, listStepsByChain, chainID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Step
	for rows.Next() {
		var i Step
		if err := rows.Scan(
			&i.ID,
			&i.ChainID,
			&i.SequenceNum,
			&i.Role,
			&i.Task,
			&i.TaskContext,
			&i.Status,
			&i.Verdict,
			&i.ReceiptPath,
			&i.TokensUsed,
			&i.TurnsUsed,
			&i.DurationSecs,
			&i.ExitCode,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startStep = `-- name: StartStep :exec
UPDATE steps
SET status = 'running',
    started_at = datetime('now')
WHERE id = ?
`

func (q *Queries) StartStep(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, startStep, id)
	return err
}

const updateChainMetrics = `-- name: UpdateChainMetrics :exec
UPDATE chains
SET total_steps = ?,
    total_tokens = ?,
    total_duration_secs = ?,
    resolver_loops = ?,
    updated_at = datetime('now')
WHERE id = ?
`

type UpdateChainMetricsParams struct {
	TotalSteps        int64  `json:"total_steps"`
	TotalTokens       int64  `json:"total_tokens"`
	TotalDurationSecs int64  `json:"total_duration_secs"`
	ResolverLoops     int64  `json:"resolver_loops"`
	ID                string `json:"id"`
}

func (q *Queries) UpdateChainMetrics(ctx context.Context, arg UpdateChainMetricsParams) error {
	_, err := q.db.ExecContext(ctx, updateChainMetrics,
		arg.TotalSteps,
		arg.TotalTokens,
		arg.TotalDurationSecs,
		arg.ResolverLoops,
		arg.ID,
	)
	return err
}

const updateChainStatus = `-- name: UpdateChainStatus :exec
UPDATE chains
SET status = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateChainStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateChainStatus(ctx context.Context, arg UpdateChainStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateChainStatus, arg.Status, arg.ID)
	return err
}
