// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: context_reports.sql

package db

import (
	"context"
	"database/sql"
)

const getContextReportByTurn = `-- name: GetContextReportByTurn :one
SELECT
    id,
    conversation_id,
    turn_number,
    analysis_latency_ms,
    retrieval_latency_ms,
    total_latency_ms,
    needs_json,
    signals_json,
    rag_results_json,
    brain_results_json,
    graph_results_json,
    explicit_files_json,
    budget_total,
    budget_used,
    budget_breakdown_json,
    included_count,
    excluded_count,
    agent_used_search_tool,
    agent_read_files_json,
    context_hit_rate,
    created_at
FROM context_reports
WHERE conversation_id = ?
  AND turn_number = ?
`

type GetContextReportByTurnParams struct {
	ConversationID string `json:"conversation_id"`
	TurnNumber     int64  `json:"turn_number"`
}

func (q *Queries) GetContextReportByTurn(ctx context.Context, arg GetContextReportByTurnParams) (ContextReport, error) {
	row := q.db.QueryRowContext(ctx, getContextReportByTurn, arg.ConversationID, arg.TurnNumber)
	var i ContextReport
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.TurnNumber,
		&i.AnalysisLatencyMs,
		&i.RetrievalLatencyMs,
		&i.TotalLatencyMs,
		&i.NeedsJson,
		&i.SignalsJson,
		&i.RagResultsJson,
		&i.BrainResultsJson,
		&i.GraphResultsJson,
		&i.ExplicitFilesJson,
		&i.BudgetTotal,
		&i.BudgetUsed,
		&i.BudgetBreakdownJson,
		&i.IncludedCount,
		&i.ExcludedCount,
		&i.AgentUsedSearchTool,
		&i.AgentReadFilesJson,
		&i.ContextHitRate,
		&i.CreatedAt,
	)
	return i, err
}

const insertContextReport = `-- name: InsertContextReport :exec
INSERT INTO context_reports (
    conversation_id,
    turn_number,
    analysis_latency_ms,
    retrieval_latency_ms,
    total_latency_ms,
    needs_json,
    signals_json,
    rag_results_json,
    brain_results_json,
    graph_results_json,
    explicit_files_json,
    budget_total,
    budget_used,
    budget_breakdown_json,
    included_count,
    excluded_count,
    agent_used_search_tool,
    agent_read_files_json,
    context_hit_rate,
    created_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type InsertContextReportParams struct {
	ConversationID      string          `json:"conversation_id"`
	TurnNumber          int64           `json:"turn_number"`
	AnalysisLatencyMs   sql.NullInt64   `json:"analysis_latency_ms"`
	RetrievalLatencyMs  sql.NullInt64   `json:"retrieval_latency_ms"`
	TotalLatencyMs      sql.NullInt64   `json:"total_latency_ms"`
	NeedsJson           sql.NullString  `json:"needs_json"`
	SignalsJson         sql.NullString  `json:"signals_json"`
	RagResultsJson      sql.NullString  `json:"rag_results_json"`
	BrainResultsJson    sql.NullString  `json:"brain_results_json"`
	GraphResultsJson    sql.NullString  `json:"graph_results_json"`
	ExplicitFilesJson   sql.NullString  `json:"explicit_files_json"`
	BudgetTotal         sql.NullInt64   `json:"budget_total"`
	BudgetUsed          sql.NullInt64   `json:"budget_used"`
	BudgetBreakdownJson sql.NullString  `json:"budget_breakdown_json"`
	IncludedCount       sql.NullInt64   `json:"included_count"`
	ExcludedCount       sql.NullInt64   `json:"excluded_count"`
	AgentUsedSearchTool sql.NullInt64   `json:"agent_used_search_tool"`
	AgentReadFilesJson  sql.NullString  `json:"agent_read_files_json"`
	ContextHitRate      sql.NullFloat64 `json:"context_hit_rate"`
	CreatedAt           string          `json:"created_at"`
}

func (q *Queries) InsertContextReport(ctx context.Context, arg InsertContextReportParams) error {
	_, err := q.db.ExecContext(ctx, insertContextReport,
		arg.ConversationID,
		arg.TurnNumber,
		arg.AnalysisLatencyMs,
		arg.RetrievalLatencyMs,
		arg.TotalLatencyMs,
		arg.NeedsJson,
		arg.SignalsJson,
		arg.RagResultsJson,
		arg.BrainResultsJson,
		arg.GraphResultsJson,
		arg.ExplicitFilesJson,
		arg.BudgetTotal,
		arg.BudgetUsed,
		arg.BudgetBreakdownJson,
		arg.IncludedCount,
		arg.ExcludedCount,
		arg.AgentUsedSearchTool,
		arg.AgentReadFilesJson,
		arg.ContextHitRate,
		arg.CreatedAt,
	)
	return err
}

const updateContextReportQuality = `-- name: UpdateContextReportQuality :exec
UPDATE context_reports
SET
    agent_used_search_tool = ?,
    agent_read_files_json = ?,
    context_hit_rate = ?
WHERE conversation_id = ?
  AND turn_number = ?
`

type UpdateContextReportQualityParams struct {
	AgentUsedSearchTool sql.NullInt64   `json:"agent_used_search_tool"`
	AgentReadFilesJson  sql.NullString  `json:"agent_read_files_json"`
	ContextHitRate      sql.NullFloat64 `json:"context_hit_rate"`
	ConversationID      string          `json:"conversation_id"`
	TurnNumber          int64           `json:"turn_number"`
}

func (q *Queries) UpdateContextReportQuality(ctx context.Context, arg UpdateContextReportQualityParams) error {
	_, err := q.db.ExecContext(ctx, updateContextReportQuality,
		arg.AgentUsedSearchTool,
		arg.AgentReadFilesJson,
		arg.ContextHitRate,
		arg.ConversationID,
		arg.TurnNumber,
	)
	return err
}
