// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation.sql

package db

import (
	"context"
	"database/sql"
)

const listConversations = `-- name: ListConversations :many
SELECT id, title, updated_at
FROM conversations
WHERE project_id = ?
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListConversationsParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

type ListConversationsRow struct {
	ID        string         `json:"id"`
	Title     sql.NullString `json:"title"`
	UpdatedAt string         `json:"updated_at"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversations, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurnMessages = `-- name: ListTurnMessages :many
SELECT id, role, content, tool_use_id, tool_name, turn_number, iteration, sequence
FROM messages
WHERE conversation_id = ?
ORDER BY sequence
`

type ListTurnMessagesRow struct {
	ID         int64          `json:"id"`
	Role       string         `json:"role"`
	Content    sql.NullString `json:"content"`
	ToolUseID  sql.NullString `json:"tool_use_id"`
	ToolName   sql.NullString `json:"tool_name"`
	TurnNumber int64          `json:"turn_number"`
	Iteration  int64          `json:"iteration"`
	Sequence   float64        `json:"sequence"`
}

func (q *Queries) ListTurnMessages(ctx context.Context, conversationID string) ([]ListTurnMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTurnMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTurnMessagesRow
	for rows.Next() {
		var i ListTurnMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Content,
			&i.ToolUseID,
			&i.ToolName,
			&i.TurnNumber,
			&i.Iteration,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reconstructConversationHistory = `-- name: ReconstructConversationHistory :many
SELECT role, content, tool_use_id, tool_name
FROM messages
WHERE conversation_id = ? AND is_compressed = 0
ORDER BY sequence
`

type ReconstructConversationHistoryRow struct {
	Role      string         `json:"role"`
	Content   sql.NullString `json:"content"`
	ToolUseID sql.NullString `json:"tool_use_id"`
	ToolName  sql.NullString `json:"tool_name"`
}

func (q *Queries) ReconstructConversationHistory(ctx context.Context, conversationID string) ([]ReconstructConversationHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, reconstructConversationHistory, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReconstructConversationHistoryRow
	for rows.Next() {
		var i ReconstructConversationHistoryRow
		if err := rows.Scan(
			&i.Role,
			&i.Content,
			&i.ToolUseID,
			&i.ToolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchConversations = `-- name: SearchConversations :many
SELECT c.id, c.title, c.updated_at, snippet(messages_fts, 0, '<b>', '</b>', '...', 32) AS snippet
FROM messages_fts
JOIN messages m ON m.id = messages_fts.rowid
JOIN conversations c ON c.id = m.conversation_id
WHERE messages_fts.content MATCH ?
ORDER BY rank
LIMIT 20
`

type SearchConversationsRow struct {
	ID        string         `json:"id"`
	Title     sql.NullString `json:"title"`
	UpdatedAt string         `json:"updated_at"`
	Snippet   string         `json:"snippet"`
}

func (q *Queries) SearchConversations(ctx context.Context, content string) ([]SearchConversationsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchConversations, content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchConversationsRow
	for rows.Next() {
		var i SearchConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.UpdatedAt,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
