// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation.sql

package db

import (
	"context"
	"database/sql"
)

const countConversations = `-- name: CountConversations :one
SELECT COUNT(*) FROM conversations WHERE project_id = ?
`

func (q *Queries) CountConversations(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConversations, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE id = ?
`

func (q *Queries) DeleteConversation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteConversation, id)
	return err
}

const deleteIterationMessages = `-- name: DeleteIterationMessages :exec
DELETE FROM messages
WHERE conversation_id = ? AND turn_number = ? AND iteration = ? AND role != 'user'
`

type DeleteIterationMessagesParams struct {
	ConversationID string `json:"conversation_id"`
	TurnNumber     int64  `json:"turn_number"`
	Iteration      int64  `json:"iteration"`
}

func (q *Queries) DeleteIterationMessages(ctx context.Context, arg DeleteIterationMessagesParams) error {
	_, err := q.db.ExecContext(ctx, deleteIterationMessages, arg.ConversationID, arg.TurnNumber, arg.Iteration)
	return err
}

const deleteIterationSubCalls = `-- name: DeleteIterationSubCalls :exec
DELETE FROM sub_calls
WHERE conversation_id = ? AND turn_number = ? AND iteration = ?
`

type DeleteIterationSubCallsParams struct {
	ConversationID sql.NullString `json:"conversation_id"`
	TurnNumber     sql.NullInt64  `json:"turn_number"`
	Iteration      sql.NullInt64  `json:"iteration"`
}

func (q *Queries) DeleteIterationSubCalls(ctx context.Context, arg DeleteIterationSubCallsParams) error {
	_, err := q.db.ExecContext(ctx, deleteIterationSubCalls, arg.ConversationID, arg.TurnNumber, arg.Iteration)
	return err
}

const deleteIterationToolExecutions = `-- name: DeleteIterationToolExecutions :exec
DELETE FROM tool_executions
WHERE conversation_id = ? AND turn_number = ? AND iteration = ?
`

type DeleteIterationToolExecutionsParams struct {
	ConversationID string `json:"conversation_id"`
	TurnNumber     int64  `json:"turn_number"`
	Iteration      int64  `json:"iteration"`
}

func (q *Queries) DeleteIterationToolExecutions(ctx context.Context, arg DeleteIterationToolExecutionsParams) error {
	_, err := q.db.ExecContext(ctx, deleteIterationToolExecutions, arg.ConversationID, arg.TurnNumber, arg.Iteration)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, project_id, title, model, provider, created_at, updated_at
FROM conversations
WHERE id = ?
`

func (q *Queries) GetConversation(ctx context.Context, id string) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Model,
		&i.Provider,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertConversation = `-- name: InsertConversation :exec
INSERT INTO conversations (id, project_id, title, model, provider, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type InsertConversationParams struct {
	ID        string         `json:"id"`
	ProjectID string         `json:"project_id"`
	Title     sql.NullString `json:"title"`
	Model     sql.NullString `json:"model"`
	Provider  sql.NullString `json:"provider"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

func (q *Queries) InsertConversation(ctx context.Context, arg InsertConversationParams) error {
	_, err := q.db.ExecContext(ctx, insertConversation,
		arg.ID,
		arg.ProjectID,
		arg.Title,
		arg.Model,
		arg.Provider,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertIterationMessage = `-- name: InsertIterationMessage :exec
INSERT INTO messages (
    conversation_id,
    role,
    content,
    tool_use_id,
    tool_name,
    turn_number,
    iteration,
    sequence,
    created_at
) VALUES (
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?,
    ?
)
`

type InsertIterationMessageParams struct {
	ConversationID string         `json:"conversation_id"`
	Role           string         `json:"role"`
	Content        sql.NullString `json:"content"`
	ToolUseID      sql.NullString `json:"tool_use_id"`
	ToolName       sql.NullString `json:"tool_name"`
	TurnNumber     int64          `json:"turn_number"`
	Iteration      int64          `json:"iteration"`
	Sequence       float64        `json:"sequence"`
	CreatedAt      string         `json:"created_at"`
}

func (q *Queries) InsertIterationMessage(ctx context.Context, arg InsertIterationMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertIterationMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.ToolUseID,
		arg.ToolName,
		arg.TurnNumber,
		arg.Iteration,
		arg.Sequence,
		arg.CreatedAt,
	)
	return err
}

const insertUserMessage = `-- name: InsertUserMessage :exec
INSERT INTO messages (
    conversation_id,
    role,
    content,
    turn_number,
    iteration,
    sequence,
    created_at
) VALUES (
    ?,
    'user',
    ?,
    ?,
    1,
    ?,
    ?
)
`

type InsertUserMessageParams struct {
	ConversationID string         `json:"conversation_id"`
	Content        sql.NullString `json:"content"`
	TurnNumber     int64          `json:"turn_number"`
	Sequence       float64        `json:"sequence"`
	CreatedAt      string         `json:"created_at"`
}

func (q *Queries) InsertUserMessage(ctx context.Context, arg InsertUserMessageParams) error {
	_, err := q.db.ExecContext(ctx, insertUserMessage,
		arg.ConversationID,
		arg.Content,
		arg.TurnNumber,
		arg.Sequence,
		arg.CreatedAt,
	)
	return err
}

const latestAssistantMessageIDForIteration = `-- name: LatestAssistantMessageIDForIteration :one
SELECT id
FROM messages
WHERE conversation_id = ?
  AND turn_number = ?
  AND iteration = ?
  AND role = 'assistant'
ORDER BY sequence DESC
LIMIT 1
`

type LatestAssistantMessageIDForIterationParams struct {
	ConversationID string `json:"conversation_id"`
	TurnNumber     int64  `json:"turn_number"`
	Iteration      int64  `json:"iteration"`
}

func (q *Queries) LatestAssistantMessageIDForIteration(ctx context.Context, arg LatestAssistantMessageIDForIterationParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestAssistantMessageIDForIteration, arg.ConversationID, arg.TurnNumber, arg.Iteration)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listActiveMessages = `-- name: ListActiveMessages :many
SELECT id, conversation_id, role, content, tool_use_id, tool_name, turn_number, iteration, sequence,
       is_compressed, is_summary, compressed_turn_start, compressed_turn_end, created_at
FROM messages
WHERE conversation_id = ? AND is_compressed = 0
ORDER BY sequence
`

func (q *Queries) ListActiveMessages(ctx context.Context, conversationID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listActiveMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.ToolUseID,
			&i.ToolName,
			&i.TurnNumber,
			&i.Iteration,
			&i.Sequence,
			&i.IsCompressed,
			&i.IsSummary,
			&i.CompressedTurnStart,
			&i.CompressedTurnEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMessages = `-- name: ListAllMessages :many
SELECT id, role, content, tool_use_id, tool_name, turn_number, iteration, sequence,
       is_compressed, is_summary, created_at
FROM messages
WHERE conversation_id = ?
ORDER BY sequence
`

type ListAllMessagesRow struct {
	ID           int64          `json:"id"`
	Role         string         `json:"role"`
	Content      sql.NullString `json:"content"`
	ToolUseID    sql.NullString `json:"tool_use_id"`
	ToolName     sql.NullString `json:"tool_name"`
	TurnNumber   int64          `json:"turn_number"`
	Iteration    int64          `json:"iteration"`
	Sequence     float64        `json:"sequence"`
	IsCompressed int64          `json:"is_compressed"`
	IsSummary    int64          `json:"is_summary"`
	CreatedAt    string         `json:"created_at"`
}

func (q *Queries) ListAllMessages(ctx context.Context, conversationID string) ([]ListAllMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllMessagesRow
	for rows.Next() {
		var i ListAllMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Content,
			&i.ToolUseID,
			&i.ToolName,
			&i.TurnNumber,
			&i.Iteration,
			&i.Sequence,
			&i.IsCompressed,
			&i.IsSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagePage = `-- name: ListMessagePage :many
SELECT id, role, content, tool_use_id, tool_name, turn_number, iteration, sequence,
       is_compressed, is_summary, created_at
FROM (
    SELECT id, role, content, tool_use_id, tool_name, turn_number, iteration, sequence,
           is_compressed, is_summary, created_at
    FROM messages
    WHERE conversation_id = ?
    ORDER BY sequence DESC
    LIMIT ? OFFSET ?
)
ORDER BY sequence
`

type ListMessagePageParams struct {
	ConversationID string `json:"conversation_id"`
	Limit          int64  `json:"limit"`
	Offset         int64  `json:"offset"`
}

type ListMessagePageRow struct {
	ID           int64          `json:"id"`
	Role         string         `json:"role"`
	Content      sql.NullString `json:"content"`
	ToolUseID    sql.NullString `json:"tool_use_id"`
	ToolName     sql.NullString `json:"tool_name"`
	TurnNumber   int64          `json:"turn_number"`
	Iteration    int64          `json:"iteration"`
	Sequence     float64        `json:"sequence"`
	IsCompressed int64          `json:"is_compressed"`
	IsSummary    int64          `json:"is_summary"`
	CreatedAt    string         `json:"created_at"`
}

func (q *Queries) ListMessagePage(ctx context.Context, arg ListMessagePageParams) ([]ListMessagePageRow, error) {
	rows, err := q.db.QueryContext(ctx, listMessagePage, arg.ConversationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMessagePageRow
	for rows.Next() {
		var i ListMessagePageRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Content,
			&i.ToolUseID,
			&i.ToolName,
			&i.TurnNumber,
			&i.Iteration,
			&i.Sequence,
			&i.IsCompressed,
			&i.IsSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversations = `-- name: ListConversations :many
SELECT id, title, updated_at
FROM conversations
WHERE project_id = ?
ORDER BY updated_at DESC
LIMIT ? OFFSET ?
`

type ListConversationsParams struct {
	ProjectID string `json:"project_id"`
	Limit     int64  `json:"limit"`
	Offset    int64  `json:"offset"`
}

type ListConversationsRow struct {
	ID        string         `json:"id"`
	Title     sql.NullString `json:"title"`
	UpdatedAt string         `json:"updated_at"`
}

func (q *Queries) ListConversations(ctx context.Context, arg ListConversationsParams) ([]ListConversationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversations, arg.ProjectID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsRow
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(&i.ID, &i.Title, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTurnMessages = `-- name: ListTurnMessages :many
SELECT id, role, content, tool_use_id, tool_name, turn_number, iteration, sequence
FROM messages
WHERE conversation_id = ?
ORDER BY sequence
`

type ListTurnMessagesRow struct {
	ID         int64          `json:"id"`
	Role       string         `json:"role"`
	Content    sql.NullString `json:"content"`
	ToolUseID  sql.NullString `json:"tool_use_id"`
	ToolName   sql.NullString `json:"tool_name"`
	TurnNumber int64          `json:"turn_number"`
	Iteration  int64          `json:"iteration"`
	Sequence   float64        `json:"sequence"`
}

func (q *Queries) ListTurnMessages(ctx context.Context, conversationID string) ([]ListTurnMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listTurnMessages, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTurnMessagesRow
	for rows.Next() {
		var i ListTurnMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.Role,
			&i.Content,
			&i.ToolUseID,
			&i.ToolName,
			&i.TurnNumber,
			&i.Iteration,
			&i.Sequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextMessageSequence = `-- name: NextMessageSequence :one
SELECT COALESCE(MAX(sequence) + 1.0, 0.0)
FROM messages
WHERE conversation_id = ?
`

func (q *Queries) NextMessageSequence(ctx context.Context, conversationID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, nextMessageSequence, conversationID)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const nextTurnNumber = `-- name: NextTurnNumber :one
SELECT COALESCE(MAX(turn_number), 0) + 1
FROM messages
WHERE conversation_id = ?
`

func (q *Queries) NextTurnNumber(ctx context.Context, conversationID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextTurnNumber, conversationID)
	var coalesce int64
	err := row.Scan(&coalesce)
	return coalesce, err
}

const reconstructConversationHistory = `-- name: ReconstructConversationHistory :many
SELECT role, content, tool_use_id, tool_name
FROM messages
WHERE conversation_id = ? AND is_compressed = 0
ORDER BY sequence
`

type ReconstructConversationHistoryRow struct {
	Role      string         `json:"role"`
	Content   sql.NullString `json:"content"`
	ToolUseID sql.NullString `json:"tool_use_id"`
	ToolName  sql.NullString `json:"tool_name"`
}

func (q *Queries) ReconstructConversationHistory(ctx context.Context, conversationID string) ([]ReconstructConversationHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, reconstructConversationHistory, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReconstructConversationHistoryRow
	for rows.Next() {
		var i ReconstructConversationHistoryRow
		if err := rows.Scan(
			&i.Role,
			&i.Content,
			&i.ToolUseID,
			&i.ToolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchConversations = `-- name: SearchConversations :many
SELECT c.id, c.title, c.updated_at, m.role, snippet(messages_fts, 0, '<b>', '</b>', '...', 32) AS snippet
FROM messages_fts
JOIN messages m ON m.id = messages_fts.rowid
JOIN conversations c ON c.id = m.conversation_id
WHERE messages_fts.content MATCH ?
ORDER BY rank
LIMIT 20
`

type SearchConversationsRow struct {
	ID        string         `json:"id"`
	Title     sql.NullString `json:"title"`
	UpdatedAt string         `json:"updated_at"`
	Role      string         `json:"role"`
	Snippet   string         `json:"snippet"`
}

func (q *Queries) SearchConversations(ctx context.Context, content string) ([]SearchConversationsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchConversations, content)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchConversationsRow
	for rows.Next() {
		var i SearchConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.UpdatedAt,
			&i.Role,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationRuntimeDefaults = `-- name: SetConversationRuntimeDefaults :exec
UPDATE conversations
SET model = ?, provider = ?, updated_at = ?
WHERE id = ?
`

type SetConversationRuntimeDefaultsParams struct {
	Model     sql.NullString `json:"model"`
	Provider  sql.NullString `json:"provider"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) SetConversationRuntimeDefaults(ctx context.Context, arg SetConversationRuntimeDefaultsParams) error {
	_, err := q.db.ExecContext(ctx, setConversationRuntimeDefaults,
		arg.Model,
		arg.Provider,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const setConversationTitle = `-- name: SetConversationTitle :exec
UPDATE conversations
SET title = ?, updated_at = ?
WHERE id = ?
`

type SetConversationTitleParams struct {
	Title     sql.NullString `json:"title"`
	UpdatedAt string         `json:"updated_at"`
	ID        string         `json:"id"`
}

func (q *Queries) SetConversationTitle(ctx context.Context, arg SetConversationTitleParams) error {
	_, err := q.db.ExecContext(ctx, setConversationTitle, arg.Title, arg.UpdatedAt, arg.ID)
	return err
}

const touchConversationUpdatedAt = `-- name: TouchConversationUpdatedAt :exec
UPDATE conversations
SET updated_at = ?
WHERE id = ?
`

type TouchConversationUpdatedAtParams struct {
	UpdatedAt string `json:"updated_at"`
	ID        string `json:"id"`
}

func (q *Queries) TouchConversationUpdatedAt(ctx context.Context, arg TouchConversationUpdatedAtParams) error {
	_, err := q.db.ExecContext(ctx, touchConversationUpdatedAt, arg.UpdatedAt, arg.ID)
	return err
}
