// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: message_compression.sql

package db

import (
	"context"
	"database/sql"
)

const insertCompressionSummary = `-- name: InsertCompressionSummary :exec
INSERT INTO messages (
    conversation_id,
    role,
    content,
    turn_number,
    iteration,
    sequence,
    is_compressed,
    is_summary,
    compressed_turn_start,
    compressed_turn_end,
    created_at
) VALUES (
    ?,
    'user',
    ?,
    ?,
    ?,
    ?,
    0,
    1,
    ?,
    ?,
    ?
)
`

type InsertCompressionSummaryParams struct {
	ConversationID      string         `json:"conversation_id"`
	Content             sql.NullString `json:"content"`
	TurnNumber          int64          `json:"turn_number"`
	Iteration           int64          `json:"iteration"`
	Sequence            float64        `json:"sequence"`
	CompressedTurnStart sql.NullInt64  `json:"compressed_turn_start"`
	CompressedTurnEnd   sql.NullInt64  `json:"compressed_turn_end"`
	CreatedAt           string         `json:"created_at"`
}

func (q *Queries) InsertCompressionSummary(ctx context.Context, arg InsertCompressionSummaryParams) error {
	_, err := q.db.ExecContext(ctx, insertCompressionSummary,
		arg.ConversationID,
		arg.Content,
		arg.TurnNumber,
		arg.Iteration,
		arg.Sequence,
		arg.CompressedTurnStart,
		arg.CompressedTurnEnd,
		arg.CreatedAt,
	)
	return err
}

const listMessagesForCompression = `-- name: ListMessagesForCompression :many
SELECT id, conversation_id, role, content, tool_use_id, tool_name, turn_number, iteration, sequence,
       is_compressed, is_summary, compressed_turn_start, compressed_turn_end, created_at
FROM messages
WHERE conversation_id = ?
ORDER BY sequence
`

func (q *Queries) ListMessagesForCompression(ctx context.Context, conversationID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesForCompression, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.ToolUseID,
			&i.ToolName,
			&i.TurnNumber,
			&i.Iteration,
			&i.Sequence,
			&i.IsCompressed,
			&i.IsSummary,
			&i.CompressedTurnStart,
			&i.CompressedTurnEnd,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessageCompressedByID = `-- name: MarkMessageCompressedByID :exec
UPDATE messages SET is_compressed = 1 WHERE id = ?
`

func (q *Queries) MarkMessageCompressedByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markMessageCompressedByID, id)
	return err
}

const markMessagesCompressedBetweenSequences = `-- name: MarkMessagesCompressedBetweenSequences :exec
UPDATE messages
SET is_compressed = 1
WHERE conversation_id = ?
  AND is_compressed = 0
  AND sequence > ?
  AND sequence < ?
`

type MarkMessagesCompressedBetweenSequencesParams struct {
	ConversationID string  `json:"conversation_id"`
	Sequence       float64 `json:"sequence"`
	Sequence_2     float64 `json:"sequence_2"`
}

func (q *Queries) MarkMessagesCompressedBetweenSequences(ctx context.Context, arg MarkMessagesCompressedBetweenSequencesParams) error {
	_, err := q.db.ExecContext(ctx, markMessagesCompressedBetweenSequences, arg.ConversationID, arg.Sequence, arg.Sequence_2)
	return err
}

const updateMessageContent = `-- name: UpdateMessageContent :exec
UPDATE messages
SET content = ?
WHERE id = ?
`

type UpdateMessageContentParams struct {
	Content sql.NullString `json:"content"`
	ID      int64          `json:"id"`
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) error {
	_, err := q.db.ExecContext(ctx, updateMessageContent, arg.Content, arg.ID)
	return err
}
