// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type BrainDocument struct {
	ID                   int64          `json:"id"`
	ProjectID            string         `json:"project_id"`
	Path                 string         `json:"path"`
	Title                sql.NullString `json:"title"`
	ContentHash          string         `json:"content_hash"`
	Tags                 sql.NullString `json:"tags"`
	Frontmatter          sql.NullString `json:"frontmatter"`
	TokenCount           sql.NullInt64  `json:"token_count"`
	CreatedBy            sql.NullString `json:"created_by"`
	SourceConversationID sql.NullString `json:"source_conversation_id"`
	CreatedAt            string         `json:"created_at"`
	UpdatedAt            string         `json:"updated_at"`
}

type BrainLink struct {
	ID         int64          `json:"id"`
	ProjectID  string         `json:"project_id"`
	SourcePath string         `json:"source_path"`
	TargetPath string         `json:"target_path"`
	LinkText   sql.NullString `json:"link_text"`
}

type Chain struct {
	ID                string         `json:"id"`
	SourceSpecs       sql.NullString `json:"source_specs"`
	SourceTask        sql.NullString `json:"source_task"`
	Status            string         `json:"status"`
	Summary           sql.NullString `json:"summary"`
	TotalSteps        int64          `json:"total_steps"`
	TotalTokens       int64          `json:"total_tokens"`
	TotalDurationSecs int64          `json:"total_duration_secs"`
	ResolverLoops     int64          `json:"resolver_loops"`
	MaxSteps          int64          `json:"max_steps"`
	MaxResolverLoops  int64          `json:"max_resolver_loops"`
	MaxDurationSecs   int64          `json:"max_duration_secs"`
	TokenBudget       int64          `json:"token_budget"`
	StartedAt         string         `json:"started_at"`
	CompletedAt       sql.NullString `json:"completed_at"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

type ContextReport struct {
	ID                  int64           `json:"id"`
	ConversationID      string          `json:"conversation_id"`
	TurnNumber          int64           `json:"turn_number"`
	AnalysisLatencyMs   sql.NullInt64   `json:"analysis_latency_ms"`
	RetrievalLatencyMs  sql.NullInt64   `json:"retrieval_latency_ms"`
	TotalLatencyMs      sql.NullInt64   `json:"total_latency_ms"`
	NeedsJson           sql.NullString  `json:"needs_json"`
	SignalsJson         sql.NullString  `json:"signals_json"`
	RagResultsJson      sql.NullString  `json:"rag_results_json"`
	BrainResultsJson    sql.NullString  `json:"brain_results_json"`
	GraphResultsJson    sql.NullString  `json:"graph_results_json"`
	ExplicitFilesJson   sql.NullString  `json:"explicit_files_json"`
	BudgetTotal         sql.NullInt64   `json:"budget_total"`
	BudgetUsed          sql.NullInt64   `json:"budget_used"`
	BudgetBreakdownJson sql.NullString  `json:"budget_breakdown_json"`
	TokenBudgetJson     sql.NullString  `json:"token_budget_json"`
	IncludedCount       sql.NullInt64   `json:"included_count"`
	ExcludedCount       sql.NullInt64   `json:"excluded_count"`
	AgentUsedSearchTool sql.NullInt64   `json:"agent_used_search_tool"`
	AgentReadFilesJson  sql.NullString  `json:"agent_read_files_json"`
	ContextHitRate      sql.NullFloat64 `json:"context_hit_rate"`
	CreatedAt           string          `json:"created_at"`
}

type Conversation struct {
	ID        string         `json:"id"`
	ProjectID string         `json:"project_id"`
	Title     sql.NullString `json:"title"`
	Model     sql.NullString `json:"model"`
	Provider  sql.NullString `json:"provider"`
	CreatedAt string         `json:"created_at"`
	UpdatedAt string         `json:"updated_at"`
}

type Event struct {
	ID        int64          `json:"id"`
	ChainID   string         `json:"chain_id"`
	StepID    sql.NullString `json:"step_id"`
	EventType string         `json:"event_type"`
	EventData sql.NullString `json:"event_data"`
	CreatedAt string         `json:"created_at"`
}

type IndexState struct {
	ID            int64  `json:"id"`
	ProjectID     string `json:"project_id"`
	FilePath      string `json:"file_path"`
	FileHash      string `json:"file_hash"`
	ChunkCount    int64  `json:"chunk_count"`
	LastIndexedAt string `json:"last_indexed_at"`
}

type Message struct {
	ID                  int64          `json:"id"`
	ConversationID      string         `json:"conversation_id"`
	Role                string         `json:"role"`
	Content             sql.NullString `json:"content"`
	ToolUseID           sql.NullString `json:"tool_use_id"`
	ToolName            sql.NullString `json:"tool_name"`
	TurnNumber          int64          `json:"turn_number"`
	Iteration           int64          `json:"iteration"`
	Sequence            float64        `json:"sequence"`
	IsCompressed        int64          `json:"is_compressed"`
	IsSummary           int64          `json:"is_summary"`
	CompressedTurnStart sql.NullInt64  `json:"compressed_turn_start"`
	CompressedTurnEnd   sql.NullInt64  `json:"compressed_turn_end"`
	CreatedAt           string         `json:"created_at"`
}

type MessagesFt struct {
	Content string `json:"content"`
}

type Project struct {
	ID                string         `json:"id"`
	Name              string         `json:"name"`
	RootPath          string         `json:"root_path"`
	Language          sql.NullString `json:"language"`
	LastIndexedCommit sql.NullString `json:"last_indexed_commit"`
	LastIndexedAt     sql.NullString `json:"last_indexed_at"`
	CreatedAt         string         `json:"created_at"`
	UpdatedAt         string         `json:"updated_at"`
}

type Step struct {
	ID           string         `json:"id"`
	ChainID      string         `json:"chain_id"`
	SequenceNum  int64          `json:"sequence_num"`
	Role         string         `json:"role"`
	Task         string         `json:"task"`
	TaskContext  sql.NullString `json:"task_context"`
	Status       string         `json:"status"`
	Verdict      sql.NullString `json:"verdict"`
	ReceiptPath  sql.NullString `json:"receipt_path"`
	TokensUsed   int64          `json:"tokens_used"`
	TurnsUsed    int64          `json:"turns_used"`
	DurationSecs int64          `json:"duration_secs"`
	ExitCode     sql.NullInt64  `json:"exit_code"`
	ErrorMessage sql.NullString `json:"error_message"`
	StartedAt    sql.NullString `json:"started_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
	CreatedAt    string         `json:"created_at"`
}

type SubCall struct {
	ID                  int64          `json:"id"`
	ConversationID      sql.NullString `json:"conversation_id"`
	MessageID           sql.NullInt64  `json:"message_id"`
	TurnNumber          sql.NullInt64  `json:"turn_number"`
	Iteration           sql.NullInt64  `json:"iteration"`
	Provider            string         `json:"provider"`
	Model               string         `json:"model"`
	Purpose             string         `json:"purpose"`
	TokensIn            int64          `json:"tokens_in"`
	TokensOut           int64          `json:"tokens_out"`
	CacheReadTokens     int64          `json:"cache_read_tokens"`
	CacheCreationTokens int64          `json:"cache_creation_tokens"`
	LatencyMs           int64          `json:"latency_ms"`
	Success             int64          `json:"success"`
	ErrorMessage        sql.NullString `json:"error_message"`
	CreatedAt           string         `json:"created_at"`
}

type ToolExecution struct {
	ID             int64          `json:"id"`
	ConversationID string         `json:"conversation_id"`
	TurnNumber     int64          `json:"turn_number"`
	Iteration      int64          `json:"iteration"`
	ToolUseID      string         `json:"tool_use_id"`
	ToolName       string         `json:"tool_name"`
	Input          sql.NullString `json:"input"`
	OutputSize     sql.NullInt64  `json:"output_size"`
	NormalizedSize sql.NullInt64  `json:"normalized_size"`
	Error          sql.NullString `json:"error"`
	Success        int64          `json:"success"`
	DurationMs     int64          `json:"duration_ms"`
	CreatedAt      string         `json:"created_at"`
}
