// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: subcalls.sql

package db

import (
	"context"
	"database/sql"
)

const insertSubCall = `-- name: InsertSubCall :exec
INSERT INTO sub_calls (
    conversation_id, message_id, turn_number, iteration,
    provider, model, purpose,
    tokens_in, tokens_out, cache_read_tokens, cache_creation_tokens,
    latency_ms, success, error_message, created_at
) VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    ?8, ?9, ?10, ?11,
    ?12, ?13, ?14, ?15
)
`

type InsertSubCallParams struct {
	ConversationID      sql.NullString `json:"conversation_id"`
	MessageID           sql.NullInt64  `json:"message_id"`
	TurnNumber          sql.NullInt64  `json:"turn_number"`
	Iteration           sql.NullInt64  `json:"iteration"`
	Provider            string         `json:"provider"`
	Model               string         `json:"model"`
	Purpose             string         `json:"purpose"`
	TokensIn            int64          `json:"tokens_in"`
	TokensOut           int64          `json:"tokens_out"`
	CacheReadTokens     int64          `json:"cache_read_tokens"`
	CacheCreationTokens int64          `json:"cache_creation_tokens"`
	LatencyMs           int64          `json:"latency_ms"`
	Success             int64          `json:"success"`
	ErrorMessage        sql.NullString `json:"error_message"`
	CreatedAt           string         `json:"created_at"`
}

func (q *Queries) InsertSubCall(ctx context.Context, arg InsertSubCallParams) error {
	_, err := q.db.ExecContext(ctx, insertSubCall,
		arg.ConversationID,
		arg.MessageID,
		arg.TurnNumber,
		arg.Iteration,
		arg.Provider,
		arg.Model,
		arg.Purpose,
		arg.TokensIn,
		arg.TokensOut,
		arg.CacheReadTokens,
		arg.CacheCreationTokens,
		arg.LatencyMs,
		arg.Success,
		arg.ErrorMessage,
		arg.CreatedAt,
	)
	return err
}
